####
http://localhost:5000/mangas

####
http://localhost:5000/manga/Berserk

###
http://localhost:5000/manga/Dr,Stone/capitulos

###
http://localhost:5000/manga/Dr,Stone/capitulo/1

###Cascada
http://localhost:5000/manga/Dr,Stone/capitulo/1/scan-traductor/Soboro/cascade

###Paginado (aun no implementado)
http://localhost:5000/manga/Dr,Stone/capitulo/1/pagina/1

###
http://localhost:5000/manga/:name/capitulo/:numero

###
http://localhost:5000/scan/:name

###
http://localhost:5000/mangaka/:name